name: learn github actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'print hello'
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'

